version: '3.8'

services:
  products:
    build: ./products
    ports:
      - "9011:9011"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  trade:
    build: ./trade
    ports:
      - "9012:9012"
    environment:
      - PRODUCT_SERVICE_ADDR=products:9011
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  grpcgateway:
    build: ./grpcgateway
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_SERVICE_ADDR=products:9011
      - TRADE_SERVICE_ADDR=trade:9012
    depends_on:
      - products
      - trade

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    ports:
      - "26379:6379" # Expose Redis on port 26379 on the host and connect to 6379 in the container
    volumes:
      - redis_data:/data # Persist Redis data on named volume

volumes:
  redis_data: # Define the volume to persist Redis data

networks:
  default: # Default network configuration